# Generated by Django 2.2.24 on 2021-08-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(choices=[('M', 'Masters'), ('B', 'Bachelors'), ('E', 'Entrance')], max_length=10)),
                ('date', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30, verbose_name='time')),
            ],
        ),
    ]
